### ISSUE TITLE
Single-node DVR install confuses easyOVS

### ISSUE THREAD

**Issue by brianphaley** [yeasy/easyOVS#10]
I know the DVR support is experimental, but I have found a bug in it.

If you have a single-node DVR system, something that's simple to do with devstack by using Q_DVR_MODE=dvr_snat in local.conf, running easyOVS 'dvr' command complains about finding an 'rfp' interface in the qrouter namespace.  This is perfectly valid in this single-node config.  Running 'dvr check compute' does run OK so the code just needs a little tweaking to detect this correctly.

**Comment by yeasy** [comment]
Thanks for the reporting!
Currently it does not supports single-node topology.
Will add it to know issues.
