### ISSUE TITLE
Install issue in liberty release

### ISSUE THREAD

**Issue by akshaysanghai** [yeasy/easyOVS#15]
I understand that easyovs has been tested till kilo release.
Not able to install in the liberty setup of openstack. Tried with the kilo setup, the installation is successful.
From the liberty setup:
git clone https://github.com/yeasy/easyOVS.git && sudo bash ./easyOVS/util/install.sh
Cloning into 'easyOVS'...
remote: Counting objects: 990, done.
remote: Total 990 (delta 0), reused 0 (delta 0), pack-reused 990
Receiving objects: 100% (990/990), 296.10 KiB | 190.00 KiB/s, done.
Resolving deltas: 100% (630/630), done.
Checking connectivity... done.
Dist = Ubuntu
Detected Linux distribution: Ubuntu 14.04 trusty amd64
### Installing easyovs dependencies

E: Unable to correct problems, you have held broken packages.

"dpkg --get-selections | grep hold" doesn't output anything

**Comment by yeasy** [comment]
Thanks for the reporting.

Could you try the docker mode, to see if it works on liberty?

Thanks!
