### ISSUE TITLE
Install in DevStack Mitaka gives error

### ISSUE THREAD

**Issue by SyCode7** [yeasy/easyOVS#16]
Install in DevStack Mitaka gives error - TypeError: dist must be a Distribution instance.

**Comment by yeasy** [comment]
Which OS are u using?

Seems dist was not detected in the util/install.sh.

**Comment by SyCode7** [comment]
Using Ubuntu 14.04.

**Comment by SyCode7** [comment]
Using Ubuntu 14.04.

**Comment by SyCode7** [comment]
Sorry for closing the issue, it was a mistake.

**Comment by yeasy** [comment]
Strange~
Are u running the cmd with root privilege?

**Comment by SyCode7** [comment]
@yeasy Thanks for the hint, I wan't not running as root. It works fine now.....great tool !!!!

**Comment by yeasy** [comment]
Thanks for your info! 
I've not tested it at Mitaka release.
Would welcome for any feedback and PRs.
Thanks!
