### ISSUE TITLE
install issue on Redhat7.3

### ISSUE THREAD

**Issue by cloudman23** [yeasy/easyOVS#18]
installing the application on Redhat7.3 / openstack Liberty  fails with error :

git clone https://github.com/yeasy/easyOVS.git && sudo bash ./easyOVS/util/install.sh
Cloning into 'easyOVS'...
remote: Counting objects: 990, done.
remote: Total 990 (delta 0), reused 0 (delta 0), pack-reused 990
Receiving objects: 100% (990/990), 296.10 KiB | 0 bytes/s, done.
Resolving deltas: 100% (630/630), done.
Dist = Redhat
Detected Linux distribution: RedHatEnterpriseServer 7.3 Maipo amd64
###Installing the dependencies and the core packages...
###Installing easyovs dependencies
###Installing easyovs core files, working dir is /tmp/easyOVS
/tmp/easyOVS /tmp
#install easyovs.1 /usr/share/man/man1
# bin/easyovs will be installed into /usr/local/bin/ in following cmd
python setup.py install  --record install.log
running install
running bdist_egg
running egg_info
creating easyovs.egg-info
writing requirements to easyovs.egg-info/requires.txt
writing easyovs.egg-info/PKG-INFO
writing top-level names to easyovs.egg-info/top_level.txt
writing dependency_links to easyovs.egg-info/dependency_links.txt
writing manifest file 'easyovs.egg-info/SOURCES.txt'
reading manifest file 'easyovs.egg-info/SOURCES.txt'
writing manifest file 'easyovs.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/easyovs
copying easyovs/__init__.py -> build/lib/easyovs
copying easyovs/bridge.py -> build/lib/easyovs
copying easyovs/bridge_ctrl.py -> build/lib/easyovs
copying easyovs/cli.py -> build/lib/easyovs
copying easyovs/common.py -> build/lib/easyovs
copying easyovs/config.py -> build/lib/easyovs
copying easyovs/dvr.py -> build/lib/easyovs
copying easyovs/flow.py -> build/lib/easyovs
copying easyovs/iptables.py -> build/lib/easyovs
copying easyovs/log.py -> build/lib/easyovs
copying easyovs/namespaces.py -> build/lib/easyovs
copying easyovs/neutron.py -> build/lib/easyovs
copying easyovs/util.py -> build/lib/easyovs
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/easyovs
copying build/lib/easyovs/__init__.py -> build/bdist.linux-x86_64/egg/easyovs
copying build/lib/easyovs/bridge.py -> build/bdist.linux-x86_64/egg/easyovs
copying build/lib/easyovs/bridge_ctrl.py -> build/bdist.linux-x86_64/egg/easyovs
copying build/lib/easyovs/cli.py -> build/bdist.linux-x86_64/egg/easyovs
copying build/lib/easyovs/common.py -> build/bdist.linux-x86_64/egg/easyovs
copying build/lib/easyovs/config.py -> build/bdist.linux-x86_64/egg/easyovs
copying build/lib/easyovs/dvr.py -> build/bdist.linux-x86_64/egg/easyovs
copying build/lib/easyovs/flow.py -> build/bdist.linux-x86_64/egg/easyovs
copying build/lib/easyovs/iptables.py -> build/bdist.linux-x86_64/egg/easyovs
copying build/lib/easyovs/log.py -> build/bdist.linux-x86_64/egg/easyovs
copying build/lib/easyovs/namespaces.py -> build/bdist.linux-x86_64/egg/easyovs
copying build/lib/easyovs/neutron.py -> build/bdist.linux-x86_64/egg/easyovs
copying build/lib/easyovs/util.py -> build/bdist.linux-x86_64/egg/easyovs
byte-compiling build/bdist.linux-x86_64/egg/easyovs/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/easyovs/bridge.py to bridge.pyc
byte-compiling build/bdist.linux-x86_64/egg/easyovs/bridge_ctrl.py to bridge_ctrl.pyc
byte-compiling build/bdist.linux-x86_64/egg/easyovs/cli.py to cli.pyc
byte-compiling build/bdist.linux-x86_64/egg/easyovs/common.py to common.pyc
byte-compiling build/bdist.linux-x86_64/egg/easyovs/config.py to config.pyc
byte-compiling build/bdist.linux-x86_64/egg/easyovs/dvr.py to dvr.pyc
byte-compiling build/bdist.linux-x86_64/egg/easyovs/flow.py to flow.pyc
byte-compiling build/bdist.linux-x86_64/egg/easyovs/iptables.py to iptables.pyc
byte-compiling build/bdist.linux-x86_64/egg/easyovs/log.py to log.pyc
byte-compiling build/bdist.linux-x86_64/egg/easyovs/namespaces.py to namespaces.pyc
byte-compiling build/bdist.linux-x86_64/egg/easyovs/neutron.py to neutron.pyc
byte-compiling build/bdist.linux-x86_64/egg/easyovs/util.py to util.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-2.7
copying and adjusting bin/easyovs -> build/scripts-2.7
changing mode of build/scripts-2.7/easyovs from 644 to 755
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/easyovs -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/easyovs to 755
copying easyovs.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying easyovs.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying easyovs.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying easyovs.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying easyovs.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/easyovs-0.5-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing easyovs-0.5-py2.7.egg
Removing /usr/lib/python2.7/site-packages/easyovs-0.5-py2.7.egg
Copying easyovs-0.5-py2.7.egg to /usr/lib/python2.7/site-packages
easyovs 0.5 is already the active version in easy-install.pth
Installing easyovs script to /usr/bin

Installed /usr/lib/python2.7/site-packages/easyovs-0.5-py2.7.egg
Processing dependencies for easyovs==0.5
Searching for python-keystoneclient<=1.6,>=1.0
Reading https://pypi.python.org/simple/python-keystoneclient/
Downloading https://pypi.python.org/packages/a2/1a/7c78d7fcad728637ea220fa28b359462c551641f39d1a8a74295dd7f46fa/python-keystoneclient-1.6.0.tar.gz#md5=7c75a78389644433f2346930ba3a3e2a
Best match: python-keystoneclient 1.6.0
Processing python-keystoneclient-1.6.0.tar.gz
Writing /tmp/easy_install-n7CxOr/python-keystoneclient-1.6.0/setup.cfg
Running python-keystoneclient-1.6.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-n7CxOr/python-keystoneclient-1.6.0/egg-dist-tmp-j5BzJI
creating /usr/lib/python2.7/site-packages/python_keystoneclient-1.6.0-py2.7.egg
Extracting python_keystoneclient-1.6.0-py2.7.egg to /usr/lib/python2.7/site-packages
Adding python-keystoneclient 1.6.0 to easy-install.pth file
Installing keystone script to /usr/bin

Installed /usr/lib/python2.7/site-packages/python_keystoneclient-1.6.0-py2.7.egg
Searching for oslo.config<=1.15,>=1.0
Reading https://pypi.python.org/simple/oslo.config/
Downloading https://pypi.python.org/packages/52/46/c2fd634069b4dfc5111e10579a7f860f0011a7bbb946bf2df10e8e37425b/oslo.config-1.15.0.tar.gz#md5=803efc8584ab0cad2e96fe7fa15241bd
Best match: oslo.config 1.15.0
Processing oslo.config-1.15.0.tar.gz
Writing /tmp/easy_install-UCXEB4/oslo.config-1.15.0/setup.cfg
Running oslo.config-1.15.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-UCXEB4/oslo.config-1.15.0/egg-dist-tmp-VcefaQ
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pbr/core.py", line 109, in pbr
    attrs = util.cfg_to_args(path)
  File "/usr/lib/python2.7/site-packages/pbr/util.py", line 245, in cfg_to_args
    kwargs = setup_cfg_to_setup_kwargs(config)
  File "/usr/lib/python2.7/site-packages/pbr/util.py", line 379, in setup_cfg_to_setup_kwargs
    cmd = cls(dist)
  File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 127, in __init__
    _Command.__init__(self, dist)
  File "/usr/lib64/python2.7/distutils/cmd.py", line 59, in __init__
    raise TypeError, "dist must be a Distribution instance"
TypeError: dist must be a Distribution instance
error: Setup script exited with error in setup command: Error parsing /tmp/easy_install-UCXEB4/oslo.config-1.15.0/setup.cfg: TypeError: dist must be a Distribution instance
make: *** [install] Error 1

**Comment by yeasy** [comment]
sorry, do not have redhat 7.3 env, anyone else met similar issue?

seems some packaging problem when setup.

**Comment by Monster0303** [comment]
return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1114, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1100, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 246, in run_setup
    raise
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 243, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 273, in run
    return func()
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 242, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-pMk4Pw/pbr-1.10.0/setup.py", line 22, in <module>
    name=distname,
  File "/usr/lib/python2.7/site-packages/pbr/util.py", line 251, in cfg_to_args
    kwargs = setup_cfg_to_setup_kwargs(config, script_args)
  File "/usr/lib/python2.7/site-packages/pbr/util.py", line 385, in setup_cfg_to_setup_kwargs
    cmd = cls(dist)
  File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 132, in __init__
    _Command.__init__(self, dist)
  File "/usr/lib64/python2.7/distutils/cmd.py", line 59, in __init__
    raise TypeError, "dist must be a Distribution instance"
TypeError: dist must be a Distribution instance
make: *** [install] error 1



Linux controller01 3.10.0-862.11.6.el7.x86_64
CentOS Linux release 7.5.1804 (Core)

**Comment by yeasy** [comment]
Sorry, do not have CentOS Linux release 7.5.1804 to test the issue. Seems a python packaging issue.
