### ISSUE TITLE
ps aux isn't always finding processes

### ISSUE THREAD

**Issue by brianphaley** [yeasy/easyOVS#9]
I'm running easyOVS on Ubuntu 14.04.  I've found when running it that it can't find any neutron processes:

> > > Checking processes...
> > > neutron-server service is not running
> > > neutron-dhcp-agent service is not running
> > > ...

If I change 'ps aux' to 'ps ax' in the code it works fine, so there could be some portability issue with the ps command where it doesn't like the 'u'.

**Comment by yeasy** [comment]
Strange!
Are you running it using Docker or locally?

**Comment by brianphaley** [comment]
I'm running it locally, no docker.

**Comment by yeasy** [comment]
Please try the docker way, it will keep clean env, and avoid system difference.

**Comment by brianphaley** [comment]
Most people don't run docker, so that isn't really a workaround, and I don't think it would help anyway.

**Comment by yeasy** [comment]
Not meet your problem, but I will look up this, to find some more robust way.
